export const characterMap = new Map<number, string>([
  [1, "Kazuya"],
  [2, "Jin"],
  [3, "King"],
  [5, "Jun"],
  [6, "Paul"],
  [7, "Law"],
  [8, "Jak"],
  [9, "Lars"],
  [10, "Ling"],
  [11, "Nina"],
  [12, "Leroy"],
  [13, "Asuka"],
  [14, "Lili"],
  [15, "Brian"],
  [16, "Hworang"],
  [17, "Claudio"],
  [18, "Azucena"],
  [19, "Raven"],
  [20, "Dragunov"],
  [21, "Shaheen"],
  [22, "Yoshimitsu"],
  [23, "Kuma"],
  [24, "Steve"],
  [25, "Leo"],
  [26, "Feng"],
  [27, "Panda"],
  [28, "Lee"],
  [29, "Alisa"],
  [30, "Zafina"],
  [31, "Devil Jin"],
  [32, "Victor"],
  [33, "Reina"],
  [34, "Eddy"],
  [35, "Lidia"],
]);
