services:
  mysql:
    container_name: 'compose-file-version'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=composed-db'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=myuser'
    ports:
      - '3307:3308'
